version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: docker/DockerfileServer
    container_name: session-container
    ports:
      - "8010:8010"
    env_file:
      - .env
    depends_on:
      - db


  db:
    build:
      context: .
      dockerfile: docker/DockerfilePostgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
      POSTGRES_PORT: 8011
      POSTGRES_HOST: db
    ports:
      - "8011:8011"
    volumes:
      - ./scheme.sql:/docker-entrypoint-initdb.d/schema.sql